spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cadu-molin/cloud-config-server

server:
  port: 9196

eureka:
  cliente:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8791/eureka/
  instance:
    hostname: localhost